### PR TITLE
Related NuCivic/internal#453 Increase external request timeout.

### PR DESCRIPTION
**Pull request by topicus**
Request timeout makes test fail. Since 500 millisec is very low
we need to increase this value to 1 sec.

### CODE REVIEW

**Comment by acouch** [comment]
I thought you meant during the test. @drkloc has a PR (https://github.com/NuCivic/recline/pull/25) to make this a setting.  Lets pull that in, then do `variable_set('recline_ajax_call_timeout', 1000)` before running the test. I found that browsers would freeze with a setting even as low as 1 second so don't want to increase the default.

**Comment by acouch** [comment]
@topicus Would it be better to use paparse to grab CSV results? Can the browser request only part of the file so it doesn't take long to load?

**Comment by topicus** [comment]
PapaParse could handle that using the stream and worker to parse files. On the other hand we are currently using time to measure weight. In other words, the time to fetch a resource does not only depends on the file size but other factors as net latency and server overhead at the download time.

We could either use papaparse as backend to prevent browser freeze on big files or make 2 queries, the first to get the file size and the second to download the file.

First is most risky and expensive because I've not tested stream parse on papaparse and it does not solve the problem completely because browser will still freeze on really big files (200mb or more). 

Second one is more cheaper, more restrictive in terms of features (we are not rendering big files) and less robust.

**Comment by topicus** [comment]
This issue is driving me crazy. Tests fails because multiple reasons:
- [ ] Fetch js timeout
  This produces the well know error "File is too large ...".
- [ ] A really weird bug with the remote_file_source
  It causes file source not being saved for authenticated users but it works for administrators. Said this, if a user with an admin role add remote resource, the bug goes away for all the roles. It seems like loading a remote file the first time runs something that only admins are enabled to do and that unblocks this for all the roles.

**Pull request closed without merging**
