### PR TITLE
Upgrade of Recline

### PR DESCRIPTION
**Pull request by ghost**
NuCivic/dkan#397

Upgrade of Recline to the latest version ( the one that uses Boostrap 3 ).
### Aceptance test
- [x] Build a new DKAN instance from branch nucivic_nucivic_internal_471_upgrade_recline
- [x] Go and check any visualization.
- [x] The new version of Recline should be used. Check that the version of Bootstrap is 3.2.0

QA Site: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com/

### CODE REVIEW

**Comment by ghost** [comment]
Removed @topicus assignation because for some reason the changes on the QA site are not working properly.

**Comment by ghost** [comment]
QA site: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com/

**Comment by topicus** [comment]
I think we have to change the css styles in screen.css and nubot radix before merge it. 

Button groups are not being properly displayed. I think there are a bunch of rules on nubot_radix and screen.css that that do not consider button groups.

screen shot 2015-03-09 at 12 26 06 pm

**Comment by teosibileau** [comment]
Everything looks good to me @topicus, if you think the following is set properly merge away

### Drush libraries-list output

screen shot 2015-03-11 at 7 52 18 pm

### Markup

screen shot 2015-03-11 at 7 51 31 pm

### Display

screen shot 2015-03-11 at 7 53 53 pm

### Data extent is working

screen shot 2015-03-11 at 7 58 56 pm
screen shot 2015-03-11 at 7 59 05 pm

**Comment by teosibileau** [comment]
Merging.

**Pull request merged**
