### PR TITLE
NuCivic/nucivic-internal#250 Implementing new recline deeplink interface

### PR DESCRIPTION
**Pull request by topicus**
NuCivic/nucivic-internal#250
## Acceptance test
- [ ] Go to data explorer
- [ ] Click on the map view button
- [ ] Change map zoom and position
- [ ] Do a browse refresh
- [ ] Map zoom and position should be preserved

### CODE REVIEW

**Comment by acouch** [comment]
@topicus When I created a QA site I find that the zoom level isn't preserved: 

327_map_zoom_.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/69f66789-ecdc-4d57-a981-716e9a2659b1#{currentView:!map,view-map:{autoZoom:true

http://327_map_zoom_.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/69f66789-ecdc-4d57-a981-716e9a2659b1#{currentView:!map,view-map:{cluster:true}}

It appears that the QA site has the latest code from your PR:
http://327_map_zoom_.dkan.qa.nuamsdev.com/profiles/dkan/modules/contrib/recline/recline.app.js

**Comment by topicus** [comment]
Seems like dist it's old. http://327_map_zoom_.dkan.qa.nuamsdev.com/profiles/dkan/libraries/recline_deeplink/dist/recline.deeplink.min.js?ni2k5t

But it's ok in the repo https://github.com/NuCivic/recline-deeplink/blob/master/dist/recline.deeplink.min.js

I think there's a commit hash over there.

**Comment by topicus** [comment]
I've just pushed an update, I forgot to update recline.make file.

**Comment by acouch** [comment]
This works for me: http://327_map_zoom_.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/66df1dbf-6193-4e55-8ab7-4c2ced4fcfd0#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},currentView:!map,graphOptions:{hooks:{processOffset:{},bindEvents:{}}},map:{bounds:{_southWest:{lat:42.95692504577836,lng:-89.62509155273438},_northEast:{lat:43.207678268758,lng:-89.15817260742188}}}}

. Can you QA @federicca ?

**Comment by teosibileau** [comment]
works for me as well -> http://327_map_zoom_.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/66df1dbf-6193-4e55-8ab7-4c2ced4fcfd0#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},currentView:!map,graphOptions:{hooks:{processOffset:{},bindEvents:{}}},map:{bounds:{_southWest:{lat:42.83166720261409,lng:-89.85855102539062},_northEast:{lat:43.33316939281732,lng:-88.92471313476562}}}}

**Pull request merged**
